<?php

namespace BlueRockTEL\SDK\Entities;

use Carbon\Carbon;
use BlueRockTEL\SDK\Entities\Entity;

class Customer extends Entity
{
    protected static $arrayCast = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'telco_exceptions_grid_uploaded_at' => 'datetime',
        'telco_exceptions_grid_taking_effect_at' => 'datetime',
        'lastInvoice' => 'datetime',
    ];

    public function __construct(
        readonly public ?int $id = null,
        readonly public int $brand_id = 1,
        readonly public ?int $representative_id = null,
        readonly public ?string $customerAccount = null,
        readonly public ?string $accountsReference = null,
        readonly public ?string $name = null,
        readonly public ?string $brand = null,
        readonly public ?string $cluster = null,
        readonly public ?string $registrationNumber = null,
        readonly public ?string $taxRegistrationNumber = null,
        readonly public ?string $mainContactFirstName = null,
        readonly public ?string $mainContactLastName = null,
        readonly public ?string $type = null,
        readonly public ?string $capital = null,
        readonly public ?string $activityCode = null,
        readonly public ?int $sector_id = null,
        readonly public ?int $origin_id = null,
        readonly public ?string $mainAddressLine1 = null,
        readonly public ?string $mainAddressLine2 = null,
        readonly public ?string $mainAddressPostalCode = null,
        readonly public ?string $mainAddressCity = null,
        readonly public ?string $mainAddressCountry = null,
        readonly public bool $abroad = false,
        readonly public int $zone = 0,
        readonly public ?string $emailAddress = null,
        readonly public ?string $accountEmailAddress = null,
        readonly public ?string $website = null,
        readonly public ?string $phone = null,
        readonly public ?string $mobilePhone = null,
        readonly public ?string $fax = null,
        readonly public ?string $logo = null,
        readonly public bool $active = true,
        readonly public ?string $activity = null,
        readonly public ?string $category = null,
        readonly public ?string $qualification = null,
        readonly public int $prospection_code_id = 1,
        readonly public bool $acceptEmails = true,
        readonly public bool $acceptCalls = true,
        readonly public bool $chargeVAT = true,
        readonly public ?string $language = null,
        readonly public bool $mergeInvoices = false,
        readonly public ?string $numberForEligibility = null,
        readonly public ?string $custom_note = null,
        readonly public ?string $technical_url = null,
        readonly public bool $isReseller = false,
        readonly public ?int $resellerLevel = 0,
        readonly public int $language_id = 1,
        readonly public ?int $supplier = 0,
        readonly public bool $applyVATAutoReverseOperators = false,
        readonly public bool $isGroupingAccount = false,
        readonly public ?string $chargeGroupingAccount = null,
        readonly public bool $isPayer = false,
        readonly public ?int $balance = null,
        readonly public ?string $motive_for_balance = null,
        readonly public bool $ftp = false,
        readonly public ?string $ftpServer = null,
        readonly public ?string $ftpUsername = null,
        readonly public ?string $ftpPassword = null,
        readonly public ?string $ftpHomeDirectory = null,
        readonly public ?string $ftpAccountId = null,
        readonly public ?string $ftpAssociatedEmail = null,
        readonly public string $suppliers = '',
        readonly public bool $onCallDuty = false,
        readonly public bool $vip = false,
        readonly public bool $canSendSms = false,
        readonly public ?string $smsAuthorisation = null,
        readonly public ?Carbon $telco_exceptions_grid_uploaded_at = null,
        readonly public ?Carbon $telco_exceptions_grid_taking_effect_at = null,
        readonly public ?int $telco_exceptions_grid_uploaded_by = null,
        readonly public bool $telco_exceptions_grid_to_redis = false,
        readonly public ?int $numberOfInvoices = null,
        readonly public ?int $lastInvoiceId = null,
        readonly public ?Carbon $lastInvoice = null,
        readonly public ?string $sms_expeditor_name = null,
        readonly public ?string $comment = null,
        readonly public bool $quickSearchIndex = false,
        readonly public ?Carbon $created_at = null,
        readonly public ?Carbon $updated_at = null,
    ) {
        //
    }
}